services:
  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_DB: dev-db

  api:
    ports:
      - "8000:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dev-db
      - SPRING_DATASOURCE_USERNAME=dev-user
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}